In [73]:
# 4	Data Profiling
# After reading the data, automatically the following details should be shown:
# a)	The number of rows
# b)	The number of columns
# c)	Number of missing values per column and their percentage
# d)	Total missing values and it’s percentage
# e)	Number of categorical columns and their list
# f)	Number of numerical columns and their list
# g)	Number of duplicate rows
# h)	Number of columns with zero standard deviation and their list
# i)	Size occupied in RAM

In [66]:
import pandas as pd
import numpy as np
import os
import psutil

In [2]:
df = pd.read_csv(r'internship_data.csv')
df.head()

,Symboling,normalized-losses,Make,Fuel_Type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [3]:
df.shape

(205, 26)

# Data profiling

In [70]:
class data_profiling:
    def __init__(self, data):
        pass
    
    def shape(self,data):
        col = []
        for i in data:
            col.append(i)
            row = len(data)
        print('Length of Row : ', row,'\n\n<==================>\n','\nLength of Columns : ', len(col))

    def question_marks(self,data):
        data = data.replace("?", value=np.nan)
        return data

    #total_count = 0    
    def missing_data(self,data):
        Missing_Col = []
        #total_count = 0
        for col in data.columns:
            total_count = 0
            count = data[col].isna().sum()
            percentage = (count/len(data))*100
            print("Column Name is : ", col," <====And===> ", " Total null Value is : ", count)
            print('Percentage of missing Value in {} is {} % : '.format(col, percentage))
            if count > 0:
                Missing_Col.append(col)
        total_count = count + total_count
        print("===================================================")
        print(" \nMissing Data Column List==>  ", Missing_Col)
        print('\n Total Missing Data is : ', total_count)
        print('\n Total percentage of missing data is {} % : '.format(total_count/len(data))*100)
        #return question_marks

    def catego_numerical(self,data):
        categorical_col = []
        numerical_col = []
        for col in data.columns:
            if data[col].dtypes == 'object':
                categorical_col.append(col)
            else:
                numerical_col.append(col)
        print('List of Categorical column : {} \n\nand their number is : {} '.format(categorical_col,len(categorical_col)))
        print('\nList of Numerical column : {} \n\nand their number is : {} '.format(numerical_col,len(numerical_col)))


    def duplicate_row(self,data):
        duplicate = data.duplicated().sum()
        print(duplicate)
        if duplicate > 0:
            duplicate.duplicated(keep = False)

    def zero_std_dvt(self,data):       
        return data.std()==0
    
    def memory_ram(self,data):
        process = psutil.Process(os.getpid())
        print(process.memory_info().rss,'bytes')

In [71]:
c1 = data_profiling(df)

In [72]:
c1.memory_ram(df)

114225152 bytes

In [152]:
df.describe()

,Symboling,Wheel-base,Length,Width,Height,Curb-weight,Engine-size,Compression-ratio,City-mpg,Highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [ ]:
# 5	Stats Based EDA


# 5.1	Steps
# MVP
# OLS
# VIF
# Correlation
# Phase1:
# Column contributions/ importance
# Annova Test
# Chi Square test
# Z test
# T -test
# Weight of Evidence 
# F – Test
# Phase 2:
# Seasonality
# Stationary Data


# 5.2	Technical solution design

            
# 5.3	Exceptions Scenarios Module Wise
# Step	Exception	Mitigation
# Column has mixed values(Integer & number)	Give proper error message	Ask the user to correct the data.
# Not all values are numbers 	Handle Internally	Convert categorical to numerical values

In [ ]:
class stats_EDA():
    
    def __init__(self,data):
        
        pass
    
    def VIF(self,data): 

    
    def Correlation(self,data):
        
    
    def Annova_test(self,data):
        
        
    def chi_square(self,data):
        
        
    def z_test(self,data):
        
        
    def t_test(self,data):

In [164]:
# class data_profiling:
#     def __init__(self, data):
#         pass
def shape(data):
    col = []
    for i in data:
        col.append(i)
        row = len(data)
    print('Length of Row : ', row,'\n\n<==================>\n','\nLength of Columns : ', len(col))


    
def question_marks(data):
    data = data.replace("?", value=np.nan)
    return data
        
#total_count = 0    
def missing_data(data):
    Missing_Col = []
    #total_count = 0
    for col in data.columns:
        total_count = 0
        count = data[col].isna().sum()
        percentage = (count/len(data))*100
        print("Column Name is : ", col," <====And===> ", " Total null Value is : ", count)
        print('Percentage of missing Value in {} is {} % : '.format(col, percentage))
        if count > 0:
            Missing_Col.append(col)
    total_count = count + total_count
    print("===================================================")
    print(" \nMissing Data Column List==>  ", Missing_Col)
    print('\n Total Missing Data is : ', total_count)
    print('\n Total percentage of missing data is {} % : '.format(total_count/len(data))*100)
    #return question_marks
        
def catego_numerical(data):
    categorical_col = []
    numerical_col = []
    for col in data.columns:
        if data[col].dtypes == 'object':
            categorical_col.append(col)
        else:
            numerical_col.append(col)
    print('List of Categorical column : {} \n\nand their number is : {} '.format(categorical_col,len(categorical_col)))
    print('\nList of Numerical column : {} \n\nand their number is : {} '.format(numerical_col,len(numerical_col)))
    
    
def duplicate_row(data):
    duplicate = data.duplicated().sum()
    print(duplicate)
    if duplicate > 0:
        duplicate.duplicated(keep = False)
        
def zero_std_dvt(data):       
    return data.std()==0